#################
#
# Products
#
#################

### get products
GET /api/product
Content-Type: application/json
Host: {{host}}

### get products
GET /api/product/search
Content-Type: application/json
Host: {{host}}