version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/go/src/app
    
  db:
    image: mysql:8.0
    tty: true
    container_name: franky_assessment_db
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: franky_assessment
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
        